[opener]
edit = [{ run = 'nvim "$@"', block = true }]
play = [{ run = 'vlc "$@"', orphan = true, for = "unix" }]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]

[manager]
ratio = [2, 3, 3]
show_symlink = true
