import = ["~/.config/alacritty/themes/tokyonight_night.toml"]

[font]
  normal = {"family" = "JetBrainsMono NF"}
  size = 14

[window]
  decorations = "None"
  opacity = 0.9

[cursor]
  style = "Beam"
